contact_links:
  - name: Github Discussions
    url: https://github.com/tidev/titanium_mobile/discussions
    about: Ask a question in Github Discussions
  - name: TiDev
    url: https://tislack.org
    about: Talk to other Titanium developers on Slack
