name: Titanium.Cloud.KeyValues
summary: Provides methods for accessing ACS Key-Values storage.
extends: Titanium.Module
excludes: { methods: [ 'addEventListener', 'fireEvent', 'removeEventListener',  ] }

methods:
  - name: append
    summary: Add the given value to the end of an existing value.
    description: |
        Requires user login. 
        
        See [Key-Values: Append to a Key-Value](http://docs.appcelerator.com/cloud/latest/#!/api/KeyValues-method-append)
        for the request parameters supported by this method.
        
        Not allowed on keyvalues with binary data.
        
        Data is returned in the `keyvalues` property of the parameter passed to the callback.
    parameters:
      - name: parameters
        summary: Parameters to send in the request.
        type: Dictionary
        
      - name: callback
        summary: Callback function to execute when the method completes.
        type: Callback<CloudKeyValuesResponse>
  
  - name: get
    summary: Retrieve a string or binary value.
    description: |
        See [Key-Value Store: Get a Value](http://docs.appcelerator.com/cloud/latest/#!/api/KeyValues-method-get)
        for the request parameters supported by this method.
        
        Data is returned in the `keyvalues` property of the parameter passed to the callback.
    parameters:
      - name: parameters
        summary: Parameters to send in the request.
        type: Dictionary
        
      - name: callback
        summary: Callback function to execute when the method completes.
        type: Callback<CloudKeyValuesResponse>
  
  - name: increment
    summary: Increment the value by the given value.
    description: |
        Requires user login. 
        
        See [Key-Values: Increment a Key-Value](http://docs.appcelerator.com/cloud/latest/#!/api/KeyValues-method-incrby)
        for the request parameters supported by this method.
        
        Not allowed on keyvalues with binary data.
        
        Data is returned in the `keyvalues` property of the parameter passed to the callback.
    parameters:
      - name: parameters
        summary: Parameters to send in the request.
        type: Dictionary

      - name: callback
        summary: Callback function to execute when the method completes.
        type: Callback<CloudKeyValuesResponse>
  
  - name: remove
    summary: Delete a value.
    description: |
        Requires user login. 
        
        See [Key-Values: Delete a Key-Value](http://docs.appcelerator.com/cloud/latest/#!/api/KeyValues-method-delete)
        for the request parameters supported by this method.
    parameters:
      - name: parameters
        summary: Parameters to send in the request.
        type: Dictionary
        
      - name: callback
        summary: Callback function to execute when the method completes.
        type: Callback<CloudKeyValuesResponse>
  
  - name: set
    summary: Sets a string or binary value referenced by the key name.
    description: |
        Requires user login. 
        
        See [Key-Value Storage: Set a string or binary value](http://docs.appcelerator.com/cloud/latest/#!/api/KeyValues-method-set)
        for the request parameters supported by this method.
    parameters:
      - name: parameters
        summary: Parameters to send in the request.
        type: Dictionary
        
      - name: callback
        summary: Callback function to execute when the method completes.
        type: Callback<CloudKeyValuesResponse>

examples:
  - title: Set a Key-Value
    example: |
        This example sets a key-value and checks the response.

            Cloud.KeyValues.set({
                name: 'welcome_message',
                value: 'Welcome to Appcelerator Cloud Services'
            }, function (e) {
                if (e.success) {
                    alert('Success');
                } else {
                    alert('Error:\n' +
                        ((e.error && e.message) || JSON.stringify(e)));
                }
            });

  - title: Get a Key-Value
    example: |
        This example gets a key-value and checks the response.

            Cloud.KeyValues.get({
                name: 'welcome_message'
            }, function (e) {
                if (e.success) {
                    var keyvalue = e.keyvalues[0];
                    alert('Success:\n' +
                        'name: ' + keyvalue.name + '\n' +
                        'value: ' + keyvalue.value);
                } else {
                    alert('Error:\n' +
                        ((e.error && e.message) || JSON.stringify(e)));
                }
            });

  - title: Append a Key-Value
    example: |
        This example appends a value to a key-value and checks the response.

            Cloud.KeyValues.append({
                name: 'welcome_message',
                value: ', take a look around'
            }, function (e) {
                 if (e.success) {
                     var keyvalue = e.keyvalues[0];
                     alert('Success:\n' +
                         'name: ' + keyvalue.name + '\n' +
                         'value: ' + keyvalue.value);
                 } else {
                     alert('Error:\n' +
                         ((e.error && e.message) || JSON.stringify(e)));
                 }

            });

  - title: Increment a Key-Value
    example: |
        This example increments a key-value and checks the response.

            Cloud.KeyValues.increment({
                name: 'score',
                value: 1
            }, function (e) {
                 if (e.success) {
                     var keyvalue = e.keyvalues[0];
                     alert('Success:\n' +
                         'name: ' + keyvalue.name + '\n' +
                         'value: ' + keyvalue.value);
                 } else {
                     alert('Error:\n' +
                         ((e.error && e.message) || JSON.stringify(e)));
                 }

            });

  - title: Remove a Key-Value
    example: |
        This example deletes a key-value and checks the response.

            Cloud.KeyValues.remove({
                name: 'welcome_message'
            }, function (e) {
                 if (e.success) {
                     alert('Success');
                 } else {
                     alert('Error:\n' +
                         ((e.error && e.message) || JSON.stringify(e)));
                 }

            });

---
name: CloudKeyValuesResponse
summary: Argument passed to the callback when a request finishes successfully or erroneously.
extends: CloudResponse
properties:
  - name: keyvalues
    summary: Set of `keyvalues` objects, if any exist.
    description: Only included if `success` is `true`.
    type: Array<Dictionary>
